a-rich/DJ-Tools

src/djtools/spotify/playlist_builder.py

Former logic was to iterate all Spotify API track search results for a single subreddit submission and add all that matched sufficiently to the corresponding playlist...
This has been corrected to sort the filtered results by fuzz ratio between the track titles and take only the best match.

Alex playlist builder one track per post

---

src/djtools/utils/README.md
src/djtools/utils/randomize_tracks.py

* generate new `TrackNumber` values using the set of tracks across all playlists being randomized (no overwriting for tracks that exist in more than one of `RANDOMIZE_TRACKS_PLAYLISTS`)
* create a single `AUTO_RANDOMIZE` playlist rather than an `AUTO_RANDOMIZE` folder with a corollary randomized playlist for each in `RANDOMIZE_TRACKS_PLAYLISTS`
* fixed missing `KeyType=0` in newly generated playlist

Alex xml track randomization

---

src/djtools/dj_tools.py
src/djtools/utils/config.py
src/djtools/utils/helpers.py

* check that basename of `--link_configs` arg **does not** exist
* check that dirname of `--link_configs` arg **does** exist
* ignore `empty.txt` in logs dir when clearing out old files (prevent accidentally packaging `djtools` without `logs` directory)

better validation for --link_configs

---

src/djtools/sync/sync_operations.py
src/djtools/utils/helpers.py
src/djtools/utils/youtube_dl.py

Replaces redundant Windows `os.makedirs` workaround code with generalized function

djtools.utils.helpers.make_dirs

---

setup.py
src/djtools/configs/helpers.py
src/djtools/rekordbox/playlist_builder.py
src/djtools/spotify/config.py
src/djtools/spotify/helpers.py
src/djtools/spotify/playlist_builder.py
src/djtools/spotify/test_helpers.py
src/djtools/spotify/test_playlist_builder.py
src/djtools/sync/helpers.py

Why?
To ensure consistency in the library and minimize error handling at the point of execution. Fix a bugs related to referencing the old subreddit configuration object.
What?
Remove all uses of "\" for line continuation. Remove unnecessary error handling in `get_subreddit_posts`. Remove erroneous validation in `async_update_auto_playlists` and erroneous referencing of dictionary members after switching to the `SubredditConfig` Pydantic model. Simplify special hip hop playlist builder logic. Remove default `ArgumentParser` options.

Config fixup

---

djtools/rekordbox/helpers.py
djtools/rekordbox/playlist_builder.py
djtools/rekordbox/test_helpers.py

feat(playlist_buildeR): print ASCII histograms of tag statistics
Why?
To quickly iterate on the proper Combiner playlist expressions, it would
be helpful if the CLI immediately output useful information to help
guide users in the right direction.
What?
Print simple ASCII tables for each TagParser implementation for each
playlist in the set of Combiner playlists generated in the run. Tables
show the frequency of each tag's apperance in each playlist. Tag
frequencies are scaled to a maximum value to constrain table heights.
TODO: Investigate vertical X-axis labels to constrain histogram width.
Investigate splitting histograms into chunks when there is a large
number of X-axis labels.

Ascii playlist stats

---

djtools/rekordbox/helpers.py
djtools/rekordbox/playlist_builder.py
djtools/rekordbox/test_helpers.py
djtools/rekordbox/test_playlist_builder.py
djtools/version.py

Why?
Printing playlist tag statistics can be quite verbose; users should have the option to suppress it by omitting `--verbosity`. Output is made more verbose than necessary by printing columns for empty tags.
What?
Move the playlist tag statistic printing logic into a helper function. Only call that function if `--verbosity` is set to a non-zero value. Pre-filter the tag data for zero values.

feat(playlists): verbosity and empty tag filter

---

.github/workflows/test.yaml
djtools/sync/sync_operations.py
setup.py
testing/sync/test_helpers.py
testing/sync/test_sync_operations.py

Why?
Neither syncing collections from multiple platforms nor syncing directory-type collections was supported.
What?
Prefix the name of the collection being synced with the PLATFORM option. Check if the local COLLECTION_PATH is a directory and append `--recursive` to the sequence of args used in the `aws` command accordingly.

feat(sync): robustify collection syncing

---

djtools/sync/helpers.py
djtools/sync/sync_operations.py
djtools/utils/helpers.py
testing/sync/test_helpers.py
testing/sync/test_sync_operations.py

Why?
The carriage return prints made by `awscli` which contain information about the amount of data and number of files transferred was getting lost due to the use of `readline()` which splits on "\n" characters.
What?
Read stdout one character at a time so the carriage return data can be displayed.
Also remove the usage of `shell=True` from all `Popen` calls.

fix: More elegant music sync

---

README.md
djtools/configs/helpers.py
scripts/xml/remove_situation_tags_and_populate_album_year_label.py

Why?
My library is missing `year`, `album`, and `label` tags. I want to remove "situation" tags ("Opener", "Build", "Peak Time") because I'm repurposing the `rating` field to convey a track's energy level.
`build_config` should permit overriding the path to `config.yaml`
What?
Adds a script to map a threaded function to a collection's tracks. The function hits the Spotify API to find a matching track and resolves the `album`, `year`, and `label` fields. In addition, the `comments` are parsed for "My Tag" data and "situation" tags are removed.
Add an optional override to `config.yaml` in the `build_config` function.

script: remove tags and populate fields

---

README.md
djtools/collection/helpers.py
testing/collection/test_helpers.py

Why?
Successful application of the `MinimalDeepTechFilter` is sensitive to the relative positioning of tags matching `Techno` (case-insensitive). Instead, the track should only need to have any tag containing the substring `techno` to be placed under a playlist called `Techno` and, similarly, any tag containing the substring `house` to be placed under a playlist called `House`. Furthermore, if a track matches both substrings , it should be placed under both playlists.
What?
Check explicitly for `house` and `techno` substrings using regex. Explicitly identify a `House` parent playlist rather than simply `not Techno`.

feat: Make `MinimalDeepTechFilter` more robust

---

.pylintrc
README.md
conftest.py
djtools/collection/collections.py
djtools/collection/helpers.py
djtools/collection/playlists.py
djtools/collection/tracks.py
djtools/configs/collection_playlists.yaml
djtools/configs/helpers.py
djtools/version.py
docs/how_to_guides/combiner_playlists.md
testing/collection/test_helpers.py
testing/data/rekordbox.xml
testing/utils/test_normalize_audio.py
testing/utils/test_url_download.py

Why?
There are multiple attributes of tracks that ought to be selectable when using build_combiner_playlists.
What?
Re-brand the former BPM and rating selector as numerical selectors and add support for release year.
Re-brand the former playlist selector as string selectors and add support for:
- artist
- comment
- date added
- key
- label
- playlist

feat: generalize string selectors

---

conftest.py
djtools/collection/collections.py
djtools/collection/copy_playlists.py
djtools/collection/playlist_builder.py
djtools/collection/shuffle_playlists.py
djtools/sync/helpers.py
docs/tutorials/getting_started/configuration.md
testing/collection/test_collections.py
testing/collection/test_copy_playlists.py
testing/collection/test_playlist_builder.py
testing/collection/test_shuffle_playlists.py
testing/sync/test_helpers.py

Why?
With the upcoming GUI work item, having to update the COLLECTION_PATH config with the "auto_" collection output when serializing would be annoying.
What?
Have collections serialize to the same path they are read from.

refactor: Collections serialize to same location

---

djtools/collection/collections.py
djtools/collection/copy_playlists.py
djtools/collection/playlist_builder.py
djtools/collection/shuffle_playlists.py
djtools/version.py
testing/collection/test_collections.py
testing/collection/test_copy_playlists.py

Why?
Collection operations should be non-destructive.
What?
shuffle_playlists and collection_playlists  no longer reset_playlists (i.e clear all data before inserting new playlists).
copy_playlists, unless an output_path is explicitly provided, will write the output collection to the same directory as
COPY_PLAYLISTS_DESTINATION.

refactor: deprecate reset_playlists

---

djtools/utils/normalize_audio.py
djtools/utils/process_recording.py
djtools/utils/url_download.py
djtools/version.py
testing/utils/test_normalize_audio.py
testing/utils/test_process_spotify_recording.py

Why?
url_download was previously writing files with a fixed mp3 codec and 320k bitrate. Also, youtube-dl does not apply postprocessors if the downloaded file is the same path as the would-be postprocessed file.
What?
Use AUDIO_FORMAT and AUDIO_BITRATE config options. Have the downloaded file use .tmp extension so postprocessing is done.
Note:
The `youtube-dl` package has bug where postprocessing of mp3s is ignored.
https://github.com/a-rich/youtube-dl/tree/fix-ffmpeg-mp3-postprocessing
test: mock pydub.AudioSegment.export and decrease verbosity
Why?
The pydub logger messes up the Github Action's ability to format test results. Also, exporting takes up valuable test time.
What?
Mock the export function properly and decrease the pydub.converter logger to CRITICAL messages in the test …

refactor: url_download uses AUDIO_* configs

---

conftest.py
djtools/collection/helpers.py
djtools/collection/playlist_builder.py
djtools/collection/playlists.py
djtools/configs/collection_playlists.yaml
djtools/configs/helpers.py
djtools/utils/config.py
djtools/version.py
testing/collection/test_helpers.py
testing/configs/test_helpers.py

Why?
To make organizing those projects easier and more flexible.
What?
Make the parts of the build_combiner_playlists call stack that touch PlaylistConfigContent.playlists work recursively.
test: suppress FFmpeg warning, test PLATFORM_REGISTRY
Why?
FFmpeg should only warn using normalize_audio or processing_recording. It should be asserted that contributions to the PLATFORM_REGISTRY object meet expectations.
What?
Add a root_validator to UtilsConfig.
Add test case for checking the type structure of PLATFORM_REGISTRY.

feat: supported nested combiner playlists

---

.github/workflows/deploy-dev-docs.yaml
.github/workflows/deploy-prod-docs.yaml
.github/workflows/release-dev.yaml
.github/workflows/release-prod.yaml
.github/workflows/test.yaml
development-requirements.txt

Why?
Bug in griffe is causing mkdocs deployments to fail (see below). Caching is good.
What?
Update mkdocstrings-python from 0.9.0 to 1.6.0. Add caching action to each workflow.

ci: cache python and update mkdocstrings-python

---

djtools/configs/cli_args.py
djtools/configs/helpers.py
testing/configs/test_cli_args.py
testing/configs/test_helpers.py

Why?
It's too easy to make a config change and forget to make a corresponding change to the CLI arg parsing logic.
What?
Move ArgumentParser from configs.helpers into configs.cli_args. Add a test that checks that every config option has a corresponding CLI arg.

refactor: test CLI args

---

.github/workflows/deploy-dev-docs.yaml
.github/workflows/deploy-prod-docs.yaml
.github/workflows/pylint.yaml
.github/workflows/pytest-coverage.yaml
.github/workflows/release-dev.yaml
.github/workflows/release-prod.yaml

Why?
Path matches for workflows were too broad.
What?
Docs deployments should only happen if markdown files underneath "docs" are touched.
Testing, linting, and releasing should only occur if Python under "djtools" are touched.

ci: restrict paths for workflow triggers

---

djtools/collection/helpers.py
djtools/collection/playlist_builder.py
djtools/collection/playlist_filters.py
docs/tutorials/developer_docs/collections_api.md
docs/tutorials/developer_docs/index.md
docs/tutorials/developer_docs/new_collections.md
docs/tutorials/developer_docs/playlist_filters.md
docs/tutorials/developer_docs/system_overview.md
mkdocs.yml
testing/collection/test_helpers.py
testing/collection/test_playlist_filters.py

Why?
Explanation about what aspects of djtools are extensible is necessary for developers to contribute.
What?
Separate PlaylistFilters into their own module. Add several docs for developers.

docs: add developer docs, playlist_filters module

---

.github/workflows/version-bump.yaml

Why?
One less commit / file edit to do manually.
What?
Edit version.py using the branch name on creation of "releases/**" branches.

ci: set version on create using branch name

---

djtools/__init__.py
djtools/collection/__init__.py
djtools/spotify/__init__.py
djtools/sync/__init__.py
djtools/utils/__init__.py

Why?
Irrelevant methods shouldn't be exported. It clutters the screen when working with djtools interactively or as a library.
What?
Don't export the *_OPERATONS dictionaries, upload_log, or initialize_logger.

refactor: cleanup the exported members

---

djtools/__init__.py
djtools/collection/__init__.py
djtools/configs/__init__.py
djtools/configs/config.py
djtools/sync/__init__.py
djtools/utils/__init__.py

Why?
When displaying configs during CLI execution, it's desirable to show each package's config separately with the BaseConfig containing only the fields exclusive to it so as to reduce clutter and organize the output...
When displaying the BaseConfig in, for example, a Python shell, it's much more useful to show the entire config instead having to access directly the fields which you cannot see.
What?
Inspect the stack frame to infer whether build_config is running as part of the CLI's execution or not.

refactor: show full BaseConfig

---

src/djtools/sync/helpers.py
tests/sync/test_helpers.py

Why?
"continue" statement was being skipped during coverage.
What?
Refactor "continue" out of upload_log logic.

test: Cython peephole optimizer fix

---

docs/how_to_guides/collection_playlists.md
docs/how_to_guides/combiner_playlists.md
docs/tutorials/developer_docs/playlist_filters.md
pyproject.toml
src/djtools/collection/config.py
src/djtools/collection/helpers.py
tests/data/collection_playlists.yaml

Why?
Combiner playlists are created using expressions that are defined in the name of the playlists themselves. As a result, playlists can have very long names. Renaming them after importing is always an option but should be done automatically when generating the playlist.
What?
Add a PlaylistName class to be used in collection_playlists.yaml.

feat: override playlist names

---

src/djtools/collection/config.py
src/djtools/collection/playlist_builder.py
src/djtools/collection/playlist_filters.py
tests/collection/test_playlist_filters.py

Why / What?
SimpleTrackFilter identifies tracks with a fewer number of non-genre tags. This can be helpful for
(a) accelerating a library maintenance task in which these tracks have
their tags augmented
(b) building a playlist which can be used in future combiner playlists
to target (in/ex)clusion of these tracks
TransitionTrackFilter identifies tracks having comments containing square bracket enclosed transition tokens which indicate that a track has one or more BPM or genre transitions.

feat: SimpleTrackFilter and TransitionTrackFilter

---

src/djtools/collection/config.py
src/djtools/collection/helpers.py
src/djtools/collection/playlist_builder.py
src/djtools/collection/playlist_filters.py
tests/collection/test_helpers.py
tests/collection/test_playlist_builder.py
tests/collection/test_playlist_filters.py

Why / What?
The TransitionTrackFilter should check all transition tokens.
The playlist_builder should remove previously built playlists, if any.
Playlist selectors should fail safely.
BooleanNode evaluation need to use a common set of operands (instead of managing tags and track sets separately) in order to evaluate correctly.
Switch SimpleTrackFilter to ComplexTrackFilter.

fix: playlist_builder

---

docs/conceptual_guides/file_standardization.md
docs/how_to_guides/check_beatcloud.md
docs/tutorials/getting_started/configuration.md
src/djtools/configs/cli_args.py
src/djtools/configs/config.py
src/djtools/sync/config.py
tests/configs/test_helpers.py

Why?
Overriding this value via the CLI is only possible if running `sync` commands. Setting `--artist-first` via the CLI should be possible also when running `utils` commands.
What?
Make ARTIST_FIRST a global config option.

fix: make ARTIST_FIRST a global option

---

conftest.py
docs/developer_docs/new_collections.md
docs/reference/collection/index.md
scripts/collection/cluster_tracks.py
scripts/collection/user_vibe_analysis.py
scripts/repair/normalize_audio.py
scripts/repair/rename_files.py
src/djtools/collection/__init__.py
src/djtools/collection/base_collection.py
src/djtools/collection/base_playlist.py
src/djtools/collection/base_track.py
src/djtools/collection/helpers.py
src/djtools/collection/playlist_filters.py
src/djtools/collection/rekordbox_collection.py
src/djtools/collection/rekordbox_playlist.py
src/djtools/collection/rekordbox_track.py
tests/collection/test_base_collection.py
tests/collection/test_base_playlist.py
tests/collection/test_base_track.py
tests/collection/test_copy_playlists.py
tests/collection/test_helpers.py
tests/collection/test_playlist_builder.py
tests/collection/test_playlist_filters.py
tests/collection/test_rekordbox_collection.py
tests/collection/test_rekordbox_playlist.py
tests/collection/test_rekordbox_track.py
tests/collection/test_shuffle_playlists.py
tests/sync/test_helpers.py

Why?
When support for platforms other than Rekordbox is added, the pre-existing modules for Collections, Playlists, and Tracks will quickly become too verbose.
What?
Split abstract base classes and Rekordbox implementations into their own modules.

refactor: split abstractions and implementations

---

pyproject.toml
src/djtools/collection/helpers.py
tests/collection/test_helpers.py

Why?
Users may want to maintain a "Recent Tracks" style of playlists.
What?
This builds on the string selector feature by adding additional processing of date selector types.
More specifically, if a date selector includes an inequality, before trying to convert the next part of the expression into a datetime, we first try and convert it into a 'ymwd' (year, month, week, day) timedelta and return a datetime offset by that timedelta instead.

feat: support timedeltas in playlist_builder

---

conftest.py
docs/how_to_guides/collection_playlists.md
docs/how_to_guides/combiner_playlists.md
pyproject.toml
scripts/collection/update_collection.py
src/djtools/collection/config.py
src/djtools/collection/helpers.py
src/djtools/collection/playlist_builder.py
tests/collection/test_config.py
tests/collection/test_helpers.py
tests/collection/test_playlist_builder.py
tests/configs/test_cli_args.py

- When building the `CollectionConfig`, look for a `configs/playlist_templates/collection_playlists.j2`
- Render that template and overwrite `configs/collection_playlists.yaml`
- Set the loaded `PlaylistConfig` object on the `CollectionConfig` (instead of validating in `CollectionConfig` and then loading in the `collection_playlists` function.
- Includes a bug fix for when trying to update `tags_tracks` with `playlist.get_tracks()` when that playlist is actually a folder

feat: Jinja templating for collection_playlists.yaml
